package com.peony.osg.model.data;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table Activity.
 */
public class DBActivity {

    private Long id;
    /** Not-null value. */
    private String name;
    private Integer type;
    private Integer status;
    private java.util.Date createTime;
    private Integer roadID;
    private Integer strength;
    private Integer venue;
    private java.util.Date beginTime;
    private java.util.Date endTime;
    private String description;
    private String images;

    public DBActivity() {
    }

    public DBActivity(Long id) {
        this.id = id;
    }

    public DBActivity(Long id, String name, Integer type, Integer status, java.util.Date createTime, Integer roadID, Integer strength, Integer venue, java.util.Date beginTime, java.util.Date endTime, String description, String images) {
        this.id = id;
        this.name = name;
        this.type = type;
        this.status = status;
        this.createTime = createTime;
        this.roadID = roadID;
        this.strength = strength;
        this.venue = venue;
        this.beginTime = beginTime;
        this.endTime = endTime;
        this.description = description;
        this.images = images;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public java.util.Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(java.util.Date createTime) {
        this.createTime = createTime;
    }

    public Integer getRoadID() {
        return roadID;
    }

    public void setRoadID(Integer roadID) {
        this.roadID = roadID;
    }

    public Integer getStrength() {
        return strength;
    }

    public void setStrength(Integer strength) {
        this.strength = strength;
    }

    public Integer getVenue() {
        return venue;
    }

    public void setVenue(Integer venue) {
        this.venue = venue;
    }

    public java.util.Date getBeginTime() {
        return beginTime;
    }

    public void setBeginTime(java.util.Date beginTime) {
        this.beginTime = beginTime;
    }

    public java.util.Date getEndTime() {
        return endTime;
    }

    public void setEndTime(java.util.Date endTime) {
        this.endTime = endTime;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getImages() {
        return images;
    }

    public void setImages(String images) {
        this.images = images;
    }

}
